cc_binary(
    name = "sfml",
    srcs = ["sfml.cpp"],
    data = ["arial.ttf"],
    linkopts = [
        "-lsfml-graphics",
        "-lsfml-window",
        "-lsfml-system",
        "-lsfml-network",
        "-lsfml-audio",
    ],
)
