cc_binary(
    name = "sfml",
    srcs = ["sfml.cpp"],
    data = ["arial.ttf"],
    linkstatic = 1,
    # linkopts = [
    #     "-lsfml-graphics",
    #     "-lsfml-window",
    #     "-lsfml-system",
    #     "-lsfml-network",
    #     "-lsfml-audio",
    # ],
    deps = ["//:sfml"],
)
