on: push
name: Bazel
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Install stuff
      run: apt-get update && apt-get install libgl1-mesa-dev libsfml-dev libpng-dev

    - name: bazel build
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: build //...
    - name: bazel test
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: test //...
